go

diff --git a/.github/workflows/lambdas-create-pr.yml b/.github/workflows/lambdas-create-pr.yml
--- a/.github/workflows/lambdas-create-pr.yml
+++ b/.github/workflows/lambdas-create-pr.yml
@@ -61,23 +61,45 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           PAT: ${{ secrets.PAT }}
+
   check-variables:
     runs-on: ubuntu-latest
     needs: load-variables
 
     steps:
-      - name: Validate Loaded Variables
+      - name: Validate JSON Outputs
         run: |
-          echo "Validating loaded variables..."
-          vars=("GITHUB_AWS_REGION" "GITHUB_AWS_ACCESS_KEY" "GITHUB_AWS_SECRET_KEY" "GITHUB_PAT_TOKEN" "TERRAFORM_DIRECTORY" "LAMBDA_RUNTIME" "LAMBDAS" "TEST_RUN_TOGGLE" "TEST_LAMBDAS" "COVERAGE_FAIL_UNDER")
-          for var in "${vars[@]}"; do
-            if [[ -z "${{ needs.load-variables.outputs[$var] }}" ]]; then
-              echo "Error: $var is empty or not defined."
-              exit 1
-            else
-              echo "$var: ${{ needs.load-variables.outputs[$var] }}"
-            fi
-          done
+          echo "Checking Lambdas Config JSON..."
+          if [[ -z "$LAMBDAS" ]]; then
+            echo "Error: LAMBDAS variable is empty or not defined."
+            exit 1
+          fi
+          echo "Lambdas Config JSON:"
+          echo "$LAMBDAS" | jq .
+          
+          echo "Checking Test Lambdas Config JSON..."
+          if [[ -z "$TEST_LAMBDAS" ]]; then
+            echo "Error: TEST_LAMBDAS variable is empty or not defined."
+            exit 1
+          fi
+          echo "Test Lambdas Config JSON:"
+          echo "$TEST_LAMBDAS" | jq .
+        env:
+          LAMBDAS: ${{ needs.load-variables.outputs.lambdas }}
+          TEST_LAMBDAS: ${{ needs.load-variables.outputs.test-lambdas }}
+
+      - name: Print All Outputs
+        run: |
+          echo "GitHub AWS Region: $GITHUB_AWS_REGION"
+          echo "GitHub AWS Access Key: $GITHUB_AWS_ACCESS_KEY"
+          echo "GitHub AWS Secret Key: $GITHUB_AWS_SECRET_KEY"
+          echo "GitHub PAT Token: $GITHUB_PAT_TOKEN"
+          echo "Terraform Directory: $TERRAFORM_DIRECTORY"
+          echo "Lambda Runtime: $LAMBDA_RUNTIME"
+          echo "Lambdas Config: $LAMBDAS"
+          echo "Test Run Toggle: $TEST_RUN_TOGGLE"
+          echo "Test Lambdas Config: $TEST_LAMBDAS"
+          echo "Coverage Fail Under: $COVERAGE_FAIL_UNDER"
         env:
           GITHUB_AWS_REGION: ${{ needs.load-variables.outputs.github-env-aws-region }}
           GITHUB_AWS_ACCESS_KEY: ${{ needs.load-variables.outputs.github-env-aws-access-key }}
@@ -89,6 +111,7 @@ jobs:
           TEST_RUN_TOGGLE: ${{ needs.load-variables.outputs.test-run-toggle }}
           TEST_LAMBDAS: ${{ needs.load-variables.outputs.test-lambdas }}
           COVERAGE_FAIL_UNDER: ${{ needs.load-variables.outputs.coverage-fail-under }}
+
   terraform-validate:
     runs-on: ubuntu-latest
     needs: load-variables
