go

diff --git a/.github/workflows/lambdas-create-pr.yml b/.github/workflows/lambdas-create-pr.yml
--- a/.github/workflows/lambdas-create-pr.yml
+++ b/.github/workflows/lambdas-create-pr.yml
@@ -8,51 +8,114 @@ on:
       - 'src/**'
       - 'tests/**'
       - 'infra/**'
-      - '.github/config/variables-lambda.env'
+      - '.github/config/variables-lambda.yml'
       - '.github/workflows/lambdas-create-pr.yml'
       - '.github/workflows/lambdas-deploy.yml'
 
 jobs:
   load-variables:
     runs-on: ubuntu-latest
+
     outputs:
-      env-file: ${{ steps.load-env.outputs.env-file }}
+      github-env-aws-region: ${{ steps.load-vars.outputs.github-env-aws-region }}
+      github-env-aws-access-key: ${{ steps.set-secrets.outputs.github-env-aws-access-key }}
+      github-env-aws-secret-key: ${{ steps.set-secrets.outputs.github-env-aws-secret-key }}
+      github-env-github-token-pat: ${{ steps.set-secrets.outputs.github-env-github-token-pat }}
+      terraform-directory: ${{ steps.load-vars.outputs.terraform-directory }}
+      lambda-runtime: ${{ steps.load-vars.outputs.lambda-runtime }}
+      lambdas: ${{ steps.load-vars.outputs.lambdas }}
+      test-run-toggle: ${{ steps.load-vars.outputs.test-run-toggle }}
+      test-lambdas: ${{ steps.load-vars.outputs.test-lambdas }}
+      coverage-fail-under: ${{ steps.load-vars.outputs.coverage-fail-under }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Load variables from .env file with expansion
-        id: load-env
-        uses: cardinalby/export-env-action@v1
-        with:
-          envFile: '.github/config/variables-lambda.env'
-          expand: 'true'
-
-      - name: Print Loaded Variables
+      - name: Load variables from YAML with yq
+        id: load-vars
         run: |
-          echo "Loaded Variables:"
-          env
+          echo "::set-output name=github-env-aws-region::$(yq '.github_env.aws.region' .github/config/variables-lambda.yml)"
+          echo "::set-output name=terraform-directory::$(yq '.terraform.directory' .github/config/variables-lambda.yml)"
+          echo "::set-output name=lambda-runtime::$(yq '.lambda.runtime' .github/config/variables-lambda.yml)"
+
+          # Processar `lambdas` como JSON e remover quebras de linha
+          lambdas=$(yq -o=json '.lambda.lambdas' .github/config/variables-lambda.yml | jq -c '.')
+          echo "::set-output name=lambdas::$lambdas"
+
+          # Processar `test-lambdas` como JSON e remover quebras de linha
+          test_lambdas=$(yq -o=json '.test.lambdas' .github/config/variables-lambda.yml | jq -c '.')
+          echo "::set-output name=test-lambdas::$test_lambdas"
+
+          # Outros parâmetros
+          echo "::set-output name=test-run-toggle::$(yq '.test.run-toogle' .github/config/variables-lambda.yml)"
+          echo "::set-output name=coverage-fail-under::$(yq '.test.coverage.fail_under' .github/config/variables-lambda.yml)"
+
+      - name: Set AWS and GitHub Secrets as Outputs
+        id: set-secrets
+        run: |
+          echo "::set-output name=github-env-aws-access-key::$AWS_ACCESS_KEY_ID"
+          echo "::set-output name=github-env-aws-secret-key::$AWS_SECRET_ACCESS_KEY"
+          echo "::set-output name=github-env-github-token-pat::$PAT"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          PAT: ${{ secrets.PAT }}
 
   check-variables:
     runs-on: ubuntu-latest
     needs: load-variables
+
     steps:
-      - name: Validate & Print Variables
+      - name: Validate JSON Outputs
         run: |
-          echo "Validating and Printing Variables..."
-          vars=("AWS_REGION" "TERRAFORM_DIRECTORY" "LAMBDA_RUNTIME" "LAMBDAS" "TEST_RUN_TOGGLE" "TEST_LAMBDAS" "COVERAGE_FAIL_UNDER")
-          for var in "${vars[@]}"; do
-            if [[ -z "${!var}" ]]; then
-              echo "Error: $var is empty or not defined."
-              exit 1
-            else
-              echo "$var: ${!var}"
-            fi
-          done
+          echo "Checking Lambdas Config JSON..."
+          if [[ -z "$LAMBDAS" ]]; then
+            echo "Error: LAMBDAS variable is empty or not defined."
+            exit 1
+          fi
+          echo "Lambdas Config JSON:"
+          echo "$LAMBDAS" | jq .
+
+          echo "Checking Test Lambdas Config JSON..."
+          if [[ -z "$TEST_LAMBDAS" ]]; then
+            echo "Error: TEST_LAMBDAS variable is empty or not defined."
+            exit 1
+          fi
+          echo "Test Lambdas Config JSON:"
+          echo "$TEST_LAMBDAS" | jq .
+        env:
+          LAMBDAS: ${{ needs.load-variables.outputs.lambdas }}
+          TEST_LAMBDAS: ${{ needs.load-variables.outputs.test-lambdas }}
+
+      - name: Print All Outputs
+        run: |
+          echo "GitHub AWS Region: $GITHUB_AWS_REGION"
+          echo "GitHub AWS Access Key: $GITHUB_AWS_ACCESS_KEY"
+          echo "GitHub AWS Secret Key: $GITHUB_AWS_SECRET_KEY"
+          echo "GitHub PAT Token: $GITHUB_PAT_TOKEN"
+          echo "Terraform Directory: $TERRAFORM_DIRECTORY"
+          echo "Lambda Runtime: $LAMBDA_RUNTIME"
+          echo "Lambdas Config: $LAMBDAS"
+          echo "Test Run Toggle: $TEST_RUN_TOGGLE"
+          echo "Test Lambdas Config: $TEST_LAMBDAS"
+          echo "Coverage Fail Under: $COVERAGE_FAIL_UNDER"
+        env:
+          GITHUB_AWS_REGION: ${{ needs.load-variables.outputs.github-env-aws-region }}
+          GITHUB_AWS_ACCESS_KEY: ${{ needs.load-variables.outputs.github-env-aws-access-key }}
+          GITHUB_AWS_SECRET_KEY: ${{ needs.load-variables.outputs.github-env-aws-secret-key }}
+          GITHUB_PAT_TOKEN: ${{ needs.load-variables.outputs.github-env-github-token-pat }}
+          TERRAFORM_DIRECTORY: ${{ needs.load-variables.outputs.terraform-directory }}
+          LAMBDA_RUNTIME: ${{ needs.load-variables.outputs.lambda-runtime }}
+          LAMBDAS: ${{ needs.load-variables.outputs.lambdas }}
+          TEST_RUN_TOGGLE: ${{ needs.load-variables.outputs.test-run-toggle }}
+          TEST_LAMBDAS: ${{ needs.load-variables.outputs.test-lambdas }}
+          COVERAGE_FAIL_UNDER: ${{ needs.load-variables.outputs.coverage-fail-under }}
 
   terraform-validate:
     runs-on: ubuntu-latest
     needs: load-variables
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -62,15 +125,16 @@ jobs:
 
       - name: Terraform Init
         run: terraform init
-        working-directory: ${{ env.TERRAFORM_DIRECTORY }}
+        working-directory: ${{ env.terraform-directory }}
 
       - name: Terraform Validate
         run: terraform validate
-        working-directory: ${{ env.TERRAFORM_DIRECTORY }}
+        working-directory: ${{ env.terraform-directory }}
 
   run-tests:
     runs-on: ubuntu-latest
     needs: terraform-validate
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -78,39 +142,85 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: ${{ env.LAMBDA_RUNTIME }}
+          python-version: ${{ env.lambda-runtime }}
 
-      - name: Install Dependencies
+      - name: Install Dependencies for All Test Directories
         run: |
-          echo "Processing test lambdas configuration..."
-          test_lambdas=$(echo "$TEST_LAMBDAS" | jq -c '.[]')
+          echo "Processing test lambdas configuration:"
+          echo "Raw $test_lambdas variable:"
+          echo "$test_lambdas"
+          
+          # Validar se a variável não está vazia
+          if [[ -z "$test_lambdas" ]]; then
+            echo "Error: test_lambda variable is empty or not defined."
+            exit 1
+          fi
+          
+          echo "Formatted test lambdas as JSON:"
+          echo "$test_lambdas" | jq '.[]'
+          
+          # Iterar sobre cada lambda
+          test_lambdas=$(echo "$test_lambdas" | jq -c '.[]')
           for test_lambda in $test_lambdas; do
             name=$(echo $test_lambda | jq -r '.name')
             source=$(echo $test_lambda | jq -r '.source')
-            echo "Processing $name in $source..."
+            echo "Processing test configuration:"
+            echo "Test Name: $name"
+            echo "Source Path: $source"
+          
+            # Validar configuração
+            if [[ -z "$name" || -z "$source" ]]; then
+              echo "Error: Invalid test lambda configuration. Name or source is missing."
+              exit 1
+            fi
+          
+            # Instalar dependências, se o arquivo requirements.txt existir
             if [ -f "$source/requirements.txt" ]; then
-              pip install -r "$source/requirements.txt"
+              echo "Installing dependencies from: $source/requirements.txt"
+              pip install -r "$source/requirements.txt" || { echo "Failed to install dependencies for $name"; exit 1; }
             else
-              echo "No requirements.txt found for $name"
+              echo "No requirements.txt found for $name in $source"
             fi
           done
+        env:
+          TEST_LAMBDAS: ${{ env.test_lambdas }}
 
-      - name: Run Tests and Generate Coverage
+
+      - name: Run All Tests and Generate Coverage Report
         run: |
           coverage run -m unittest discover -s tests
-          coverage report -m --fail-under=$COVERAGE_FAIL_UNDER
+          coverage report -m --fail-under=$coverage-fail-under
           coverage html
           coverage-badge -o coverage.svg -f
 
+      - name: Organize Coverage Reports
+        run: |
+          mkdir -p tests/reports
+          mv htmlcov tests/reports/htmlcov
+          mv coverage.svg tests/reports/coverage.svg
+
+      - name: Upload Coverage Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-report
+          path: tests/reports/htmlcov
+
+      - name: Upload Coverage Badge
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-badge
+          path: tests/reports/coverage.svg
+
   sync-develop-to-main:
     runs-on: ubuntu-latest
-    needs: run-tests
+    needs: [terraform-validate, run-tests]
     if: success()
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Fetch and Checkout Branches
+      - name: Sync develop to main
         run: |
           git fetch origin
           git checkout develop
@@ -124,12 +234,12 @@ jobs:
           git merge --no-ff ${{ github.event.pull_request.head.ref }}
           git push origin develop
         env:
-          GITHUB_PAT: ${{ secrets.PAT }}
+          token: ${{ needs.load-variables.outputs.github-env-github-token-pat }}
 
       - name: Create or Update Pull Request to Main
         uses: actions/github-script@v6
         with:
-          github-token: ${{ secrets.PAT }}
+          github-token: ${{ needs.load-variables.outputs.github-env-github-token-pat }}
           script: |
             const { data: existingPullRequests } = await github.rest.pulls.list({
               owner: context.repo.owner,
@@ -160,4 +270,3 @@ jobs:
                 draft: false
               });
               console.log(`Created pull request: ${pullRequest.html_url}`);
-            }
