go?

diff --git a/.github/workflows/lambdas-create-pr.yml b/.github/workflows/lambdas-create-pr.yml
--- a/.github/workflows/lambdas-create-pr.yml
+++ b/.github/workflows/lambdas-create-pr.yml
@@ -35,28 +35,23 @@ jobs:
       - name: Load variables from YAML with yq
         id: load-vars
         run: |
-          echo "::set-output name=github-env-aws-region::$(yq '.github_env.aws.region' .github/config/variables-lambda.yml)"
-          echo "::set-output name=terraform-directory::$(yq '.terraform.directory' .github/config/variables-lambda.yml)"
-          echo "::set-output name=lambda-runtime::$(yq '.lambda.runtime' .github/config/variables-lambda.yml)"
-
-          # Processar `lambdas` como JSON e remover quebras de linha
-          lambdas=$(yq -o=json '.lambda.lambdas' .github/config/variables-lambda.yml | jq -rc '.')
-          echo "::set-output name=lambdas::$lambdas"
-
-          # Processar `test-lambdas` como JSON e remover quebras de linha
-          test_lambdas=$(yq -o=json '.test.lambdas' .github/config/variables-lambda.yml | jq -rc '.')
-          echo "::set-output name=test-lambdas::$test_lambdas"
-
-          # Outros parâmetros
-          echo "::set-output name=test-run-toggle::$(yq '.test.run-toogle' .github/config/variables-lambda.yml)"
-          echo "::set-output name=coverage-fail-under::$(yq '.test.coverage.fail_under' .github/config/variables-lambda.yml)"
+          echo "github-env-aws-region=$(yq '.github_env.aws.region' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          echo "terraform-directory=$(yq '.terraform.directory' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          echo "lambda-runtime=$(yq '.lambda.runtime' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          
+          # Processar lambdas e test-lambdas como JSON
+          echo "lambdas=$(yq -o=json '.lambda.lambdas' .github/config/variables-lambda.yml | jq -c '.')" >> $GITHUB_ENV
+          echo "test-lambdas=$(yq -o=json '.test.lambdas' .github/config/variables-lambda.yml | jq -c '.')" >> $GITHUB_ENV
+          
+          echo "test-run-toggle=$(yq '.test.run-toogle' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          echo "coverage-fail-under=$(yq '.test.coverage.fail_under' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
 
       - name: Set AWS and GitHub Secrets as Outputs
         id: set-secrets
         run: |
-          echo "::set-output name=github-env-aws-access-key::$AWS_ACCESS_KEY_ID"
-          echo "::set-output name=github-env-aws-secret-key::$AWS_SECRET_ACCESS_KEY"
-          echo "::set-output name=github-env-github-token-pat::$PAT"
+          echo "github-env-aws-access-key=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
+          echo "github-env-aws-secret-key=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
+          echo "github-env-github-token-pat=$PAT" >> $GITHUB_ENV
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -65,22 +60,22 @@ jobs:
       - name: Validate JSON Outputs
         run: |
           echo "Lambdas Config JSON:"
-          echo '${{ steps.load-vars.outputs.lambdas }}' | jq .
+          echo "$lambdas" | jq .
           echo "Test Lambdas Config JSON:"
-          echo '${{ steps.load-vars.outputs.test-lambdas }}' | jq .
+          echo "$test-lambdas" | jq .
 
       - name: Print All Outputs
         run: |
-          echo "GitHub AWS Region: ${{ steps.load-vars.outputs.github-env-aws-region }}"
-          echo "GitHub AWS Access Key: ${{ steps.set-secrets.outputs.github-env-aws-access-key }}"
-          echo "GitHub AWS Secret Key: ${{ steps.set-secrets.outputs.github-env-aws-secret-key }}"
-          echo "GitHub PAT Token: ${{ steps.set-secrets.outputs.github-env-github-token-pat }}"
-          echo "Terraform Directory: ${{ steps.load-vars.outputs.terraform-directory }}"
-          echo "Lambda Runtime: ${{ steps.load-vars.outputs.lambda-runtime }}"
-          echo "Lambdas Config: ${{ steps.load-vars.outputs.lambdas }}"
-          echo "Test Run Toggle: ${{ steps.load-vars.outputs.test-run-toggle }}"
-          echo "Test Lambdas Config: ${{ steps.load-vars.outputs.test-lambdas }}"
-          echo "Coverage Fail Under: ${{ steps.load-vars.outputs.coverage-fail-under }}"
+          echo "GitHub AWS Region: $github-env-aws-region"
+          echo "GitHub AWS Access Key: $github-env-aws-access-key"
+          echo "GitHub AWS Secret Key: $github-env-aws-secret-key"
+          echo "GitHub PAT Token: $github-env-github-token-pat"
+          echo "Terraform Directory: $terraform-directory"
+          echo "Lambda Runtime: $lambda-runtime"
+          echo "Lambdas Config: $lambdas"
+          echo "Test Run Toggle: $test-run-toggle"
+          echo "Test Lambdas Config: $test-lambdas"
+          echo "Coverage Fail Under: $coverage-fail-under"
 
   terraform-validate:
     runs-on: ubuntu-latest
@@ -95,16 +90,15 @@ jobs:
 
       - name: Terraform Init
         run: terraform init
-        working-directory: ${{ needs.load-variables.outputs.terraform-directory }}
+        working-directory: ${{ env.terraform-directory }}
 
       - name: Terraform Validate
         run: terraform validate
-        working-directory: ${{ needs.load-variables.outputs.terraform-directory }}
+        working-directory: ${{ env.terraform-directory }}
 
   run-tests:
     runs-on: ubuntu-latest
     needs: terraform-validate
-    if: ${{ needs.load-variables.outputs.test-run-toggle == 'true' }}
 
     steps:
       - name: Checkout repository
@@ -113,24 +107,20 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: ${{ needs.load-variables.outputs.lambda-runtime }}
+          python-version: ${{ env.lambda-runtime }}
 
       - name: Install Dependencies for All Test Directories
         run: |
           echo "Processing test lambdas configuration:"
           echo "Raw test-lambdas variable:"
-          echo '${{ needs.load-variables.outputs.test-lambdas }}'
+          echo "$test-lambdas"
 
-          # Validar se a variável não está vazia
-          if [[ -z '${{ needs.load-variables.outputs.test-lambdas }}' ]]; then
+          if [[ -z "$test-lambdas" ]]; then
             echo "Error: test-lambdas variable is empty or not defined."
             exit 1
           fi
 
-          echo "Formatted test lambdas as JSON:"
-          echo '${{ needs.load-variables.outputs.test-lambdas }}' | jq '.[]'
-
-          test_lambdas=$(echo '${{ needs.load-variables.outputs.test-lambdas }}' | jq -c '.[]')
+          test_lambdas=$(echo "$test-lambdas" | jq -c '.[]')
 
           for test_lambda in $test_lambdas; do
             name=$(echo $test_lambda | jq -r '.name')
@@ -146,20 +136,16 @@ jobs:
 
             if [ -f "$source/requirements.txt" ]; then
               echo "Installing dependencies from: $source/requirements.txt"
-              pip install -r "$source/requirements.txt" || { echo "Failed to install dependencies for $name"; exit 1; }
+              pip install -r "$source/requirements.txt" || exit 1
             else
               echo "No requirements.txt found for $name in $source"
             fi
           done
 
-      - name: Ensure Coverage is Installed
-        run: |
-          pip install coverage coverage-badge
-
       - name: Run All Tests and Generate Coverage Report
         run: |
           coverage run -m unittest discover -s tests
-          coverage report -m --fail-under=${{ needs.load-variables.outputs.coverage-fail-under }}
+          coverage report -m --fail-under=$coverage-fail-under
           coverage html
           coverage-badge -o coverage.svg -f
 
