testes

diff --git a/.github/workflows/lambdas-create-pr.yml b/.github/workflows/lambdas-create-pr.yml
--- a/.github/workflows/lambdas-create-pr.yml
+++ b/.github/workflows/lambdas-create-pr.yml
@@ -16,18 +16,6 @@ jobs:
   load-variables:
     runs-on: ubuntu-latest
 
-    outputs:
-      github-env-aws-region: ${{ steps.load-vars.outputs.github-env-aws-region }}
-      github-env-aws-access-key: ${{ steps.set-secrets.outputs.github-env-aws-access-key }}
-      github-env-aws-secret-key: ${{ steps.set-secrets.outputs.github-env-aws-secret-key }}
-      github-env-github-token-pat: ${{ steps.set-secrets.outputs.github-env-github-token-pat }}
-      terraform-directory: ${{ steps.load-vars.outputs.terraform-directory }}
-      lambda-runtime: ${{ steps.load-vars.outputs.lambda-runtime }}
-      lambdas: ${{ steps.load-vars.outputs.lambdas }}
-      test-run-toggle: ${{ steps.load-vars.outputs.test-run-toggle }}
-      test-lambdas: ${{ steps.load-vars.outputs.test-lambdas }}
-      coverage-fail-under: ${{ steps.load-vars.outputs.coverage-fail-under }}
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -35,32 +23,26 @@ jobs:
       - name: Load variables from YAML with yq
         id: load-vars
         run: |
-          echo "::set-output name=github-env-aws-region::$(yq '.github_env.aws.region' .github/config/variables-lambda.yml)"
-          echo "::set-output name=terraform-directory::$(yq '.terraform.directory' .github/config/variables-lambda.yml)"
-          echo "::set-output name=lambda-runtime::$(yq '.lambda.runtime' .github/config/variables-lambda.yml)"
+          echo "AWS_REGION=$(yq '.github_env.aws.region' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          echo "TERRAFORM_DIRECTORY=$(yq '.terraform.directory' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          echo "LAMBDA_RUNTIME=$(yq '.lambda.runtime' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
 
-          # Processar `lambdas` como JSON e remover quebras de linha
+          # Processar `lambdas` como JSON e armazenar no GITHUB_ENV
           lambdas=$(yq -o=json '.lambda.lambdas' .github/config/variables-lambda.yml | jq -c '.')
-          echo "::set-output name=lambdas::$lambdas"
+          echo "LAMBDAS=$lambdas" >> $GITHUB_ENV
 
-          # Processar `test-lambdas` como JSON e remover quebras de linha
+          # Processar `test-lambdas` como JSON e armazenar no GITHUB_ENV
           test_lambdas=$(yq -o=json '.test.lambdas' .github/config/variables-lambda.yml | jq -c '.')
-          echo "::set-output name=test-lambdas::$test_lambdas"
+          echo "TEST_LAMBDAS=$test_lambdas" >> $GITHUB_ENV
 
-          # Outros parâmetros
-          echo "::set-output name=test-run-toggle::$(yq '.test.run-toogle' .github/config/variables-lambda.yml)"
-          echo "::set-output name=coverage-fail-under::$(yq '.test.coverage.fail_under' .github/config/variables-lambda.yml)"
+          echo "TEST_RUN_TOGGLE=$(yq '.test.run-toogle' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
+          echo "COVERAGE_FAIL_UNDER=$(yq '.test.coverage.fail_under' .github/config/variables-lambda.yml)" >> $GITHUB_ENV
 
-      - name: Set AWS and GitHub Secrets as Outputs
-        id: set-secrets
+      - name: Set AWS and GitHub Secrets
         run: |
-          echo "::set-output name=github-env-aws-access-key::$AWS_ACCESS_KEY_ID"
-          echo "::set-output name=github-env-aws-secret-key::$AWS_SECRET_ACCESS_KEY"
-          echo "::set-output name=github-env-github-token-pat::$PAT"
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          PAT: ${{ secrets.PAT }}
+          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
+          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
+          echo "GITHUB_PAT=${{ secrets.PAT }}" >> $GITHUB_ENV
 
   check-variables:
     runs-on: ubuntu-latest
@@ -69,48 +51,25 @@ jobs:
     steps:
       - name: Validate JSON Outputs
         run: |
-          echo "Checking Lambdas Config JSON..."
-          if [[ -z "$LAMBDAS" ]]; then
-            echo "Error: LAMBDAS variable is empty or not defined."
-            exit 1
-          fi
+          echo "Validating JSON Outputs..."
           echo "Lambdas Config JSON:"
           echo "$LAMBDAS" | jq .
 
-          echo "Checking Test Lambdas Config JSON..."
-          if [[ -z "$TEST_LAMBDAS" ]]; then
-            echo "Error: TEST_LAMBDAS variable is empty or not defined."
-            exit 1
-          fi
           echo "Test Lambdas Config JSON:"
           echo "$TEST_LAMBDAS" | jq .
-        env:
-          LAMBDAS: ${{ needs.load-variables.outputs.lambdas }}
-          TEST_LAMBDAS: ${{ needs.load-variables.outputs.test-lambdas }}
 
       - name: Print All Outputs
         run: |
-          echo "GitHub AWS Region: $GITHUB_AWS_REGION"
-          echo "GitHub AWS Access Key: $GITHUB_AWS_ACCESS_KEY"
-          echo "GitHub AWS Secret Key: $GITHUB_AWS_SECRET_KEY"
-          echo "GitHub PAT Token: $GITHUB_PAT_TOKEN"
+          echo "GitHub AWS Region: $AWS_REGION"
+          echo "GitHub AWS Access Key: $AWS_ACCESS_KEY_ID"
+          echo "GitHub AWS Secret Key: $AWS_SECRET_ACCESS_KEY"
+          echo "GitHub PAT Token: $GITHUB_PAT"
           echo "Terraform Directory: $TERRAFORM_DIRECTORY"
           echo "Lambda Runtime: $LAMBDA_RUNTIME"
           echo "Lambdas Config: $LAMBDAS"
           echo "Test Run Toggle: $TEST_RUN_TOGGLE"
           echo "Test Lambdas Config: $TEST_LAMBDAS"
           echo "Coverage Fail Under: $COVERAGE_FAIL_UNDER"
-        env:
-          GITHUB_AWS_REGION: ${{ needs.load-variables.outputs.github-env-aws-region }}
-          GITHUB_AWS_ACCESS_KEY: ${{ needs.load-variables.outputs.github-env-aws-access-key }}
-          GITHUB_AWS_SECRET_KEY: ${{ needs.load-variables.outputs.github-env-aws-secret-key }}
-          GITHUB_PAT_TOKEN: ${{ needs.load-variables.outputs.github-env-github-token-pat }}
-          TERRAFORM_DIRECTORY: ${{ needs.load-variables.outputs.terraform-directory }}
-          LAMBDA_RUNTIME: ${{ needs.load-variables.outputs.lambda-runtime }}
-          LAMBDAS: ${{ needs.load-variables.outputs.lambdas }}
-          TEST_RUN_TOGGLE: ${{ needs.load-variables.outputs.test-run-toggle }}
-          TEST_LAMBDAS: ${{ needs.load-variables.outputs.test-lambdas }}
-          COVERAGE_FAIL_UNDER: ${{ needs.load-variables.outputs.coverage-fail-under }}
 
   terraform-validate:
     runs-on: ubuntu-latest
@@ -125,11 +84,11 @@ jobs:
 
       - name: Terraform Init
         run: terraform init
-        working-directory: ${{ env.terraform-directory }}
+        working-directory: $TERRAFORM_DIRECTORY
 
       - name: Terraform Validate
         run: terraform validate
-        working-directory: ${{ env.terraform-directory }}
+        working-directory: $TERRAFORM_DIRECTORY
 
   run-tests:
     runs-on: ubuntu-latest
@@ -142,54 +101,41 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: ${{ env.lambda-runtime }}
+          python-version: $LAMBDA_RUNTIME
 
       - name: Install Dependencies for All Test Directories
         run: |
-          echo "Processing test lambdas configuration:"
-          echo "Raw $test_lambdas variable:"
-          echo "$test_lambdas"
-          
-          # Validar se a variável não está vazia
-          if [[ -z "$test_lambdas" ]]; then
-            echo "Error: test_lambda variable is empty or not defined."
+          echo "Processing test lambdas configuration..."
+          echo "Raw test lambdas variable:"
+          echo "$TEST_LAMBDAS"
+
+          if [[ -z "$TEST_LAMBDAS" ]]; then
+            echo "Error: TEST_LAMBDAS is empty."
             exit 1
           fi
-          
-          echo "Formatted test lambdas as JSON:"
-          echo "$test_lambdas" | jq '.[]'
-          
-          # Iterar sobre cada lambda
-          test_lambdas=$(echo "$test_lambdas" | jq -c '.[]')
+
+          test_lambdas=$(echo "$TEST_LAMBDAS" | jq -c '.[]')
           for test_lambda in $test_lambdas; do
             name=$(echo $test_lambda | jq -r '.name')
             source=$(echo $test_lambda | jq -r '.source')
-            echo "Processing test configuration:"
-            echo "Test Name: $name"
-            echo "Source Path: $source"
-          
-            # Validar configuração
+
             if [[ -z "$name" || -z "$source" ]]; then
-              echo "Error: Invalid test lambda configuration. Name or source is missing."
+              echo "Error: Invalid test lambda configuration."
               exit 1
             fi
-          
-            # Instalar dependências, se o arquivo requirements.txt existir
+
             if [ -f "$source/requirements.txt" ]; then
-              echo "Installing dependencies from: $source/requirements.txt"
-              pip install -r "$source/requirements.txt" || { echo "Failed to install dependencies for $name"; exit 1; }
+              echo "Installing dependencies from $source/requirements.txt"
+              pip install -r "$source/requirements.txt" || exit 1
             else
-              echo "No requirements.txt found for $name in $source"
+              echo "No requirements.txt found for $name"
             fi
           done
-        env:
-          TEST_LAMBDAS: ${{ env.test_lambdas }}
-
 
       - name: Run All Tests and Generate Coverage Report
         run: |
           coverage run -m unittest discover -s tests
-          coverage report -m --fail-under=$coverage-fail-under
+          coverage report -m --fail-under=$COVERAGE_FAIL_UNDER
           coverage html
           coverage-badge -o coverage.svg -f
 
@@ -234,12 +180,12 @@ jobs:
           git merge --no-ff ${{ github.event.pull_request.head.ref }}
           git push origin develop
         env:
-          token: ${{ needs.load-variables.outputs.github-env-github-token-pat }}
+          GITHUB_PAT: $GITHUB_PAT
 
       - name: Create or Update Pull Request to Main
         uses: actions/github-script@v6
         with:
-          github-token: ${{ needs.load-variables.outputs.github-env-github-token-pat }}
+          github-token: $GITHUB_PAT
           script: |
             const { data: existingPullRequests } = await github.rest.pulls.list({
               owner: context.repo.owner,
